[SERVICE]
    Name            docker

[INPUT]
    Name            docker
    Tag             logs.*
    Path            /var/run/docker.sock
    DB              /var/log/flb_docker.db
    Mem_Buf_Limit   5MB

[FILTER]
    Name            modify
    Match           *
    Add             cluster airport-platform
    Add             environment dev

[OUTPUT]
    Name            loki
    Match           *
    Host            loki
    Port            3100
    URI             /loki/api/v1/push
    Labels          {job="docker"}
    Line_format     json
    Auto_kubernetes_labels false
