apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: airport-platform
  labels:
    app: identity-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: identity-service
