apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: airport-platform
type: Opaque
stringData:
  DB_USERNAME: "admin"
  DB_PASSWORD: "supersecret"  # In production, this comes from Vault
